### ISSUE TITLE
Does not seem to build. Using the latest android NDK

### ISSUE THREAD

**Issue by rhcp011235** [dosomder/iovyroot#2]
rhcps-Mac-Pro-2:jni rhcp$  ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk
[armeabi] Compile arm    : iovyroot <= main.c
./main.c: In function 'writemsg':
./main.c:93:9: error: variable 'msg' has initializer but incomplete type
  struct mmsghdr msg = {{ 0 }, 0 };
         ^
./main.c:93:9: error: extra brace group at end of initializer
./main.c:93:9: error: (near initialization for 'msg')
./main.c:93:9: warning: excess elements in struct initializer
./main.c:93:9: warning: (near initialization for 'msg')
./main.c:93:9: warning: excess elements in struct initializer
./main.c:93:9: warning: (near initialization for 'msg')
./main.c:93:17: error: storage size of 'msg' isn't known
  struct mmsghdr msg = {{ 0 }, 0 };
                 ^
./main.c:101:2: warning: implicit declaration of function 'socket' [-Wimplicit-function-declaration]
  sockfd = socket(AF_INET, SOCK_DGRAM, 0);
  ^
./main.c:101:27: error: 'SOCK_DGRAM' undeclared (first use in this function)
  sockfd = socket(AF_INET, SOCK_DGRAM, 0);
                           ^
./main.c:101:27: note: each undeclared identifier is reported only once for each function it appears in
./main.c:108:2: warning: implicit declaration of function 'connect' [-Wimplicit-function-declaration]
  if (connect(sockfd, (struct sockaddr _)&soaddr, sizeof(soaddr)) == -1) 
  ^
./main.c:121:3: warning: implicit declaration of function 'sendmmsg' [-Wimplicit-function-declaration]
   sendmmsg(sockfd, &msg, 1, 0);
   ^
./main.c:93:17: warning: unused variable 'msg' [-Wunused-variable]
  struct mmsghdr msg = {{ 0 }, 0 };
                 ^
./main.c: In function 'getpipes':
./main.c:234:26: error: 'F_SETPIPE_SZ' undeclared (first use in this function)
  ret = (fcntl(pipefd[1], F_SETPIPE_SZ, PIPESZ) == PIPESZ) ? 0 : 1;
                          ^
make: *_\* [obj/local/armeabi/objs/iovyroot/main.o] Error 1

**Comment by dosomder** [comment]
Your system doesn't seem to use the `Application.mk` of this project. You are missing this parameter
`NDK_APPLICATION_MK=Application.mk`

**Comment by rhcp011235** [comment]
Would you happen to know what the correct command line would be to build this?

On Wed, Apr 6, 2016 at 4:01 AM, dosomder notifications@github.com wrote:
Your system doesn't seem to use the Application.mk of this project.

**Comment by rhcp011235** [comment]
Oh sorry I missed the bottom part! Let me try that. Thank you

**Comment by dosomder** [comment]
If you go one folder up (out of jni), it should be suffice to just run `ndk-build` without any parameters.

**Comment by rhcp011235** [comment]
Yep both ways fixed it :) 

Thanks was stupid of me.
