### ISSUE TITLE
can't work on SOV31

### ISSUE THREAD

**Issue by meiyy** [dosomder/iovyroot#21]
info:
28.0.D.6.136 with  kernel 3.10.49-perf-geaad5d9 Mon Oct 19 17:21:43 2015
I build it with ndk-r10e and run with adb shell,but my phone always get crashed when
"[+] Removing JOP",then restart with red light.
So why does this happen?
thx

**Comment by dosomder** [comment]
I'm not sure. You could add more logging here: https://github.com/dosomder/iovyroot/blob/master/jni/main.c#L346 to see where exactly the crash happens.

**Comment by meiyy** [comment]
It seems to work fine now with the latest code in main.c .Thanks.

**Comment by meiyy** [comment]
It seems to work fine now with the latest code in main.c .Thanks.
