### ISSUE TITLE
Nexus 5, 5.0.1 LRX22C

### ISSUE THREAD

**Issue by superpwn** [dosomder/iovyroot#23]
please add this

`{ "Nexus 5", "Linux version 3.4.0-g88fbc66 (android-build@vpbs1.mtv.corp.google.com) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Mon Oct 20 22:18:31 UTC 2014",
      { (void*)FSYNC_OFFSET(0xc1236cd8) },
      (void*)0xc122ecc0, (void*)0xc122ebb0, (void*)0xc1076be0, (void*)0xc122d164 }`

thanks

**Comment by dosomder** [comment]
Thank you :+1:
